blank_issues_enabled: true
contact_links:
  - name: 💬 电报讨论群组
    url: https://t.me/+zFImOziSNullOTE1
    about: 加入我们的 Telegram 群组进行讨论和获取帮助
  - name: 📖 项目文档
    url: https://github.com/14790897/handwriting-web/blob/master/README.md
    about: 查看项目文档和使用说明
